export const lightColors = {
  background: "#E7DFD2",
  secondaryBackground: "#f2f2f2",
  inputBoxBackground: "#DBCFBA",
  text: "#1F1F1F",
  subheadtextcolor: "#1F1F1F",
  icons: "#e68a00",
  button: "black",
  buttonText: "#0D0D0D",
  buttonBackground: "#B3DCD6",
  cardbackground: "#CFC3B0",
  cardComponentColor: "#EDE6DA",
  placeholderBackGroundColor: "#DED7CC",
  primarytextcolor: "#0D0D0D",
  secondarytextcolor: "#0D0D0D",
  searchresulttextcolor: "#454D4B",
  searchplaceholdercolor: "#877D6D",
  commontextcolor: "#E7DFD2",
  iconcolor: "#D1CABE",
  donebuttontextcolor: "#191815",
  addplaceholdertextcolor: "#B4B4B4",
  tabBarBackgroundColor: "#F5EEE4",
  tabactiveTintColor: "#67DCCB",
  subheadingtextcolor: "#8B8B8B",
  editProfilebuttonTextColor: "#000000",
  borderColor: "#D6CAB6",
  textHeadingColor: "#333333",
  textDescriptionColor: "#807B74",
  onBoardingViewColor: "#ACACAC",
  saveAlbumTintColor:"#67DCCB",
};

// Dark theme colors
export const darkColors = {
  background: "#0D0D0D",
  secondaryBackground: "#1e1e1e",
  // inputBoxBackground: "#3E4040",
  inputBoxBackground: "#1A1816",
  text: "#A19A92",
  subheadtextcolor: "#A19A92",
  icons: "orange",
  button: "orange",
  cardComponentColor: "#1A1813",
  buttonText: "#0D0D0D",
  buttonBackground: "#B3DCD6",
  cardbackground: "#1A1816",
  // cardComponentColor:'#191813',
  placeholderBackGroundColor: "#242322",
  primarytextcolor: "#E7DFD2",
  secondarytextcolor: "#E7DFD2",
  searchresulttextcolor: "#8C8780",
  searchplaceholdercolor: "#877D6D",
  commontextcolor: "#E7DFD2",
  iconcolor: "#D1CABE",
  donebuttontextcolor: "#E7DFD2",
  addplaceholdertextcolor: "#666666",
  tabBarBackgroundColor: "#000000",
  tabactiveTintColor: "#67DCCB",
  subheadingtextcolor: "#8B8B8B",
  editProfilebuttonTextColor: "#E7DFD2",
  borderColor: "#141414",
  textHeadingColor: "#E7DFD2",
  textDescriptionColor: "#807B74",
  onBoardingViewColor: "#5C5C5C",
  saveAlbumTintColor:"#67DCCB",

};
